"""fix(ai): update embedding dimensions to 3072

Revision ID: 04c6445c606d
Revises: 2033e5c6a21a
Create Date: 2026-03-31 22:20:05.544462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "04c6445c606d"
down_revision: Union[str, Sequence[str], None] = "2033e5c6a21a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "business_units",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "business_units",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.drop_index(
        op.f("uq_capitados_monthly_records_active"),
        table_name="capitados_monthly_records",
        postgresql_where="(rolled_back_at IS NULL)",
    )
    op.drop_index(
        op.f("uq_capitados_product_insureds_active"),
        table_name="capitados_product_insureds",
        postgresql_where="(rolled_back_at IS NULL)",
    )
    op.drop_index(
        op.f("ix_chat_conversations_workspace_id"), table_name="chat_conversations"
    )
    op.create_index(
        op.f("ix_chat_conversations_company_id"),
        "chat_conversations",
        ["company_id"],
        unique=False,
    )
    op.alter_column(
        "countries",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "country_zone",
        "zone_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "country_zone",
        "country_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("memberships_business_unit_business_unit_id_fkey"),
        "memberships_business_unit",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("memberships_business_unit_user_id_fkey"),
        "memberships_business_unit",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "memberships_business_unit",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "memberships_business_unit",
        "business_units",
        ["business_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "zones",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "zones",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_constraint(None, "memberships_business_unit", type_="foreignkey")
    op.drop_constraint(None, "memberships_business_unit", type_="foreignkey")
    op.create_foreign_key(
        op.f("memberships_business_unit_user_id_fkey"),
        "memberships_business_unit",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("memberships_business_unit_business_unit_id_fkey"),
        "memberships_business_unit",
        "business_units",
        ["business_unit_id"],
        ["id"],
    )
    op.alter_column(
        "knowledge_documents",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        existing_nullable=True,
    )
    op.alter_column(
        "country_zone",
        "country_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.alter_column(
        "country_zone",
        "zone_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.alter_column(
        "countries",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(
        op.f("ix_chat_conversations_company_id"), table_name="chat_conversations"
    )
    op.create_index(
        op.f("ix_chat_conversations_workspace_id"),
        "chat_conversations",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("uq_capitados_product_insureds_active"),
        "capitados_product_insureds",
        ["product_id", "document_number", "status"],
        unique=True,
        postgresql_where="(rolled_back_at IS NULL)",
    )
    op.create_index(
        op.f("uq_capitados_monthly_records_active"),
        "capitados_monthly_records",
        ["product_id", "person_id", "coverage_month", "status"],
        unique=True,
        postgresql_where="(rolled_back_at IS NULL)",
    )
    op.drop_column("business_units", "updated_at")
    op.drop_column("business_units", "created_at")
    # ### end Alembic commands ###
