"""policy_version_snapshot

Revision ID: 800269a4b3d2
Revises: f726ec0a5b70
Create Date: 2026-03-31 12:17:10.887234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.shared.base_model

# revision identifiers, used by Alembic.
revision: str = "800269a4b3d2"
down_revision: Union[str, Sequence[str], None] = "f726ec0a5b70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clients_company_id"), table_name="clients")
    op.drop_index(
        op.f("ix_commission_distributions_company_id"),
        table_name="commission_distributions",
    )
    op.drop_index(op.f("ix_user_workspaces_workspace_id"), table_name="company_user")
    op.alter_column(
        "customer_profiles",
        "home_address_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "customer_profiles",
        "billing_address_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "customer_profiles",
        "tags",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_leads_company_id"), table_name="leads")
    op.alter_column("plans", "product_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index(op.f("ix_plans_company_id"), table_name="plans")
    op.add_column(
        "policies",
        sa.Column("plan_version_id", app.shared.base_model.GUID(), nullable=False),
    )
    op.drop_index(op.f("ix_policies_company_id"), table_name="policies")
    op.create_foreign_key(
        None, "policies", "plan_versions", ["plan_version_id"], ["id"]
    )
    op.drop_index(op.f("ix_subscriptions_company_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_transactions_company_id"), table_name="transactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_transactions_company_id"), "transactions", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_company_id"),
        "subscriptions",
        ["company_id"],
        unique=False,
    )
    op.drop_constraint(None, "policies", type_="foreignkey")
    op.create_index(
        op.f("ix_policies_company_id"), "policies", ["company_id"], unique=False
    )
    op.drop_column("policies", "plan_version_id")
    op.create_index(op.f("ix_plans_company_id"), "plans", ["company_id"], unique=False)
    op.alter_column("plans", "product_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(op.f("ix_leads_company_id"), "leads", ["company_id"], unique=False)
    op.alter_column(
        "customer_profiles",
        "tags",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "customer_profiles",
        "billing_address_json",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "customer_profiles",
        "home_address_json",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_user_workspaces_workspace_id"),
        "company_user",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_commission_distributions_company_id"),
        "commission_distributions",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clients_company_id"), "clients", ["company_id"], unique=False
    )
    # ### end Alembic commands ###
