"""capitados_system

Revision ID: cb69a9898ec4
Revises: eb37207d3580
Create Date: 2026-03-31 13:51:57.023401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.shared.base_model


# revision identifiers, used by Alembic.
revision: str = "cb69a9898ec4"
down_revision: Union[str, Sequence[str], None] = "eb37207d3580"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capitados_void_reasons",
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capitados_void_reasons_id"),
        "capitados_void_reasons",
        ["id"],
        unique=False,
    )
    op.create_table(
        "capitados_batch_logs",
        sa.Column("company_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("coverage_month", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_file_id", sa.BigInteger(), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("created_by_user_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("rolled_back_at", sa.DateTime(), nullable=True),
        sa.Column(
            "rolled_back_by_user_id", app.shared.base_model.GUID(), nullable=True
        ),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("total_applied", sa.Integer(), nullable=False),
        sa.Column("total_rejected", sa.Integer(), nullable=False),
        sa.Column("total_duplicated", sa.Integer(), nullable=False),
        sa.Column("total_incongruences", sa.Integer(), nullable=False),
        sa.Column("total_plan_errors", sa.Integer(), nullable=False),
        sa.Column("total_rolled_back", sa.Integer(), nullable=False),
        sa.Column("is_any_month_allowed", sa.Boolean(), nullable=False),
        sa.Column("cutoff_day", sa.Integer(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("summary_json", sa.JSON(), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rolled_back_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capitados_batch_logs_id"), "capitados_batch_logs", ["id"], unique=False
    )
    op.create_table(
        "capitados_product_insureds",
        sa.Column("company_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("product_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("document_number", sa.String(length=64), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("sex", sa.String(length=1), nullable=False),
        sa.Column("residence_country_id", sa.Integer(), nullable=True),
        sa.Column("repatriation_country_id", sa.Integer(), nullable=True),
        sa.Column("age_reported", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("rolled_back_at", sa.DateTime(), nullable=True),
        sa.Column(
            "rolled_back_by_user_id", app.shared.base_model.GUID(), nullable=True
        ),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repatriation_country_id"],
            ["countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["residence_country_id"],
            ["countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rolled_back_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capitados_product_insureds_id"),
        "capitados_product_insureds",
        ["id"],
        unique=False,
    )
    op.create_table(
        "capitados_contracts",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("company_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("product_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("person_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("entry_age", sa.Integer(), nullable=True),
        sa.Column("wtime_suicide_ends_at", sa.Date(), nullable=True),
        sa.Column("wtime_preexisting_conditions_ends_at", sa.Date(), nullable=True),
        sa.Column("wtime_accident_ends_at", sa.Date(), nullable=True),
        sa.Column("terminated_at", sa.DateTime(), nullable=True),
        sa.Column("termination_reason", sa.Text(), nullable=True),
        sa.Column("rolled_back_at", sa.DateTime(), nullable=True),
        sa.Column(
            "rolled_back_by_user_id", app.shared.base_model.GUID(), nullable=True
        ),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["capitados_product_insureds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rolled_back_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_capitados_contracts_id"), "capitados_contracts", ["id"], unique=False
    )
    op.create_table(
        "capitados_monthly_records",
        sa.Column("company_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("product_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("person_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("contract_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("coverage_month", sa.Date(), nullable=False),
        sa.Column("plan_version_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("load_batch_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("sex", sa.String(length=1), nullable=False),
        sa.Column("age_reported", sa.Integer(), nullable=True),
        sa.Column("residence_country_id", sa.Integer(), nullable=True),
        sa.Column("repatriation_country_id", sa.Integer(), nullable=True),
        sa.Column("price_base", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_source", sa.String(length=32), nullable=True),
        sa.Column("age_surcharge_rule_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column(
            "age_surcharge_percent", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "age_surcharge_amount", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("price_final", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("rolled_back_at", sa.DateTime(), nullable=True),
        sa.Column(
            "rolled_back_by_user_id", app.shared.base_model.GUID(), nullable=True
        ),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["age_surcharge_rule_id"],
            ["plan_version_age_surcharges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["capitados_contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["load_batch_id"],
            ["capitados_batch_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["capitados_product_insureds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_version_id"],
            ["plan_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repatriation_country_id"],
            ["countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["residence_country_id"],
            ["countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rolled_back_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capitados_monthly_records_id"),
        "capitados_monthly_records",
        ["id"],
        unique=False,
    )
    op.create_table(
        "capitados_batch_item_logs",
        sa.Column("batch_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("sheet_name", sa.String(length=128), nullable=True),
        sa.Column("row_number", sa.Integer(), nullable=True),
        sa.Column("product_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("plan_version_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("residence_raw", sa.String(length=255), nullable=True),
        sa.Column("residence_code_extracted", sa.String(length=8), nullable=True),
        sa.Column("repatriation_raw", sa.String(length=255), nullable=True),
        sa.Column("repatriation_code_extracted", sa.String(length=8), nullable=True),
        sa.Column("residence_country_id", sa.Integer(), nullable=True),
        sa.Column("repatriation_country_id", sa.Integer(), nullable=True),
        sa.Column("document_number", sa.String(length=64), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("sex", sa.String(length=1), nullable=True),
        sa.Column("age_reported", sa.Integer(), nullable=True),
        sa.Column("result", sa.String(length=32), nullable=True),
        sa.Column("rejection_code", sa.String(length=64), nullable=True),
        sa.Column("rejection_detail", sa.Text(), nullable=True),
        sa.Column("person_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("contract_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("monthly_record_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("duplicated_record_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["capitados_batch_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["capitados_contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["duplicated_record_id"],
            ["capitados_monthly_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["monthly_record_id"],
            ["capitados_monthly_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["capitados_product_insureds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_version_id"],
            ["plan_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repatriation_country_id"],
            ["countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["residence_country_id"],
            ["countries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capitados_batch_item_logs_id"),
        "capitados_batch_item_logs",
        ["id"],
        unique=False,
    )

    # Partial unique indexes for active records (rolled_back_at IS NULL)
    op.create_index(
        "uq_capitados_product_insureds_active",
        "capitados_product_insureds",
        ["product_id", "document_number", "status"],
        unique=True,
        postgresql_where=sa.text("rolled_back_at IS NULL"),
    )
    op.create_index(
        "uq_capitados_monthly_records_active",
        "capitados_monthly_records",
        ["product_id", "person_id", "coverage_month", "status"],
        unique=True,
        postgresql_where=sa.text("rolled_back_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_capitados_monthly_records_active", table_name="capitados_monthly_records"
    )
    op.drop_index(
        "uq_capitados_product_insureds_active", table_name="capitados_product_insureds"
    )
    op.drop_index(
        op.f("ix_capitados_batch_item_logs_id"), table_name="capitados_batch_item_logs"
    )
    op.drop_table("capitados_batch_item_logs")
    op.drop_index(
        op.f("ix_capitados_monthly_records_id"), table_name="capitados_monthly_records"
    )
    op.drop_table("capitados_monthly_records")
    op.drop_index(op.f("ix_capitados_contracts_id"), table_name="capitados_contracts")
    op.drop_table("capitados_contracts")
    op.drop_index(
        op.f("ix_capitados_product_insureds_id"),
        table_name="capitados_product_insureds",
    )
    op.drop_table("capitados_product_insureds")
    op.drop_index(op.f("ix_capitados_batch_logs_id"), table_name="capitados_batch_logs")
    op.drop_table("capitados_batch_logs")
    op.drop_index(
        op.f("ix_capitados_void_reasons_id"), table_name="capitados_void_reasons"
    )
    op.drop_table("capitados_void_reasons")
    # ### end Alembic commands ###
