"""Auth profiles and rbac updates

Revision ID: ce81c153f259
Revises: 1b249b89876e
Create Date: 2026-03-31 11:32:21.741894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision: str = "ce81c153f259"
down_revision: Union[str, Sequence[str], None] = "1b249b89876e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_profiles",
        sa.Column("user_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("mobile_e164", sa.String(length=20), nullable=True),
        sa.Column("alt_email", sa.String(length=190), nullable=True),
        sa.Column("doc_type", sa.String(length=30), nullable=True),
        sa.Column("doc_number", sa.Text(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("male", "female", "other", name="customer_gender_enum"),
            nullable=True,
        ),
        sa.Column(
            "home_address_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "preferred_language",
            sa.Enum("es", "en", name="customer_lang_enum"),
            nullable=False,
        ),
        sa.Column(
            "contact_via",
            sa.Enum("email", "whatsapp", "sms", name="customer_contact_enum"),
            nullable=False,
        ),
        sa.Column("emergency_name", sa.String(length=160), nullable=True),
        sa.Column("emergency_phone_e164", sa.String(length=20), nullable=True),
        sa.Column("emergency_relation", sa.String(length=60), nullable=True),
        sa.Column("billing_name", sa.String(length=160), nullable=True),
        sa.Column("tax_id", sa.String(length=40), nullable=True),
        sa.Column(
            "billing_address_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("notes_internal", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "password_histories",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("password_hash", sa.String(length=191), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_histories_user_id"),
        "password_histories",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "staff_profiles",
        sa.Column("user_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("work_phone", sa.String(length=30), nullable=True),
        sa.Column(
            "commission_regular_first_year_pct",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column(
            "commission_regular_renewal_pct",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column(
            "commission_capitados_pct", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("notes_admin", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.drop_column("company_user", "is_owner")
    op.drop_column("company_user", "joined_at")
    op.add_column(
        "permissions", sa.Column("guard_name", sa.String(length=191), nullable=False)
    )
    op.add_column(
        "permissions", sa.Column("description", sa.String(length=255), nullable=True)
    )
    op.alter_column(
        "permissions",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=191),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("permissions_name_key"), "permissions", type_="unique")
    op.create_unique_constraint(
        "permissions_name_guard_name_unique", "permissions", ["name", "guard_name"]
    )
    op.add_column(
        "roles", sa.Column("guard_name", sa.String(length=191), nullable=False)
    )
    op.add_column("roles", sa.Column("scope", sa.String(length=50), nullable=True))
    op.add_column("roles", sa.Column("level", sa.Integer(), nullable=False))
    op.add_column("roles", sa.Column("label", sa.Text(), nullable=True))
    op.alter_column(
        "roles",
        "name",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=191),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("roles_name_key"), "roles", type_="unique")
    op.create_index(op.f("ix_roles_scope"), "roles", ["scope"], unique=False)
    op.create_unique_constraint(
        "roles_name_guard_name_unique", "roles", ["name", "guard_name"]
    )

    # --- Data Migration ---
    op.execute("""
        UPDATE roles SET scope = 'customer', guard_name = 'web' WHERE name = 'CLIENTE';
    """)
    op.execute("""
        UPDATE roles SET scope = 'staff', guard_name = 'web' WHERE name != 'CLIENTE';
    """)

    op.execute("""
        INSERT INTO customer_profiles (user_id, created_at, updated_at, preferred_language, contact_via)
        SELECT u.user_id, NOW(), NOW(), 'es', 'email'
        FROM user_roles u
        JOIN roles r ON u.role_id = r.id
        WHERE r.scope = 'customer'
        ON CONFLICT (user_id) DO NOTHING;
    """)

    op.execute("""
        INSERT INTO staff_profiles (user_id, created_at, updated_at)
        SELECT u.user_id, NOW(), NOW()
        FROM user_roles u
        JOIN roles r ON u.role_id = r.id
        WHERE r.scope = 'staff'
        ON CONFLICT (user_id) DO NOTHING;
    """)

    op.execute("""
        INSERT INTO password_histories (user_id, password_hash, created_at)
        SELECT id, hashed_password, NOW() FROM users;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("roles_name_guard_name_unique", "roles", type_="unique")
    op.drop_index(op.f("ix_roles_scope"), table_name="roles")
    op.create_unique_constraint(
        op.f("roles_name_key"), "roles", ["name"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "roles",
        "name",
        existing_type=sa.String(length=191),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("roles", "label")
    op.drop_column("roles", "level")
    op.drop_column("roles", "scope")
    op.drop_column("roles", "guard_name")
    op.drop_constraint(
        "permissions_name_guard_name_unique", "permissions", type_="unique"
    )
    op.create_unique_constraint(
        op.f("permissions_name_key"),
        "permissions",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "permissions",
        "name",
        existing_type=sa.String(length=191),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("permissions", "description")
    op.drop_column("permissions", "guard_name")
    op.add_column(
        "company_user",
        sa.Column(
            "joined_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "company_user",
        sa.Column("is_owner", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_table("staff_profiles")
    op.drop_index(
        op.f("ix_password_histories_user_id"), table_name="password_histories"
    )
    op.drop_table("password_histories")
    op.drop_table("customer_profiles")
    # ### end Alembic commands ###
