"""baseline_and_geography

Revision ID: cfcc3aa64589
Revises:
Create Date: 2026-03-31 08:25:28.765362

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.shared.base_model
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "cfcc3aa64589"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("name", sa.JSON(), nullable=False),
        sa.Column("iso2", sa.CHAR(length=2), nullable=True),
        sa.Column("iso3", sa.CHAR(length=3), nullable=True),
        sa.Column("continent_code", sa.String(length=2), nullable=False),
        sa.Column("phone_code", sa.String(length=10), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iso2"),
        sa.UniqueConstraint("iso3"),
    )
    op.create_index(
        op.f("ix_countries_continent_code"),
        "countries",
        ["continent_code"],
        unique=False,
    )
    op.create_index(op.f("ix_countries_id"), "countries", ["id"], unique=False)
    op.create_index(
        op.f("ix_countries_is_active"), "countries", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_countries_phone_code"), "countries", ["phone_code"], unique=False
    )
    op.create_table(
        "coverages",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("limit_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("limit_unit", sa.String(length=50), nullable=True),
        sa.Column("notes_es", sa.Text(), nullable=True),
        sa.Column("notes_en", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_coverages_id"), "coverages", ["id"], unique=False)
    op.create_table(
        "permissions",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_permissions_id"), "permissions", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_table(
        "stripe_events",
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stripe_events_event_id"), "stripe_events", ["event_id"], unique=True
    )
    op.create_index(op.f("ix_stripe_events_id"), "stripe_events", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_reseller", sa.Boolean(), nullable=False),
        sa.Column("stripe_connect_id", sa.String(length=100), nullable=True),
        sa.Column("commission_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workspaces_id"), "workspaces", ["id"], unique=False)
    op.create_index(op.f("ix_workspaces_slug"), "workspaces", ["slug"], unique=True)
    op.create_table(
        "zones",
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_zones_id"), "zones", ["id"], unique=False)
    op.create_index(op.f("ix_zones_is_active"), "zones", ["is_active"], unique=False)
    op.create_index(op.f("ix_zones_name"), "zones", ["name"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("workspace_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("old_values", sa.JSON(), nullable=True),
        sa.Column("new_values", sa.JSON(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column("details", sa.String(length=1000), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_logs_action_created_at",
        "audit_logs",
        ["action", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_entity_entity_id",
        "audit_logs",
        ["entity", "entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        "ix_audit_logs_user_id_created_at",
        "audit_logs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_workspace_id"), "audit_logs", ["workspace_id"], unique=False
    )
    op.create_table(
        "chat_conversations",
        sa.Column("workspace_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("user_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("context_snapshot", sa.JSON(), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_conversations_id"), "chat_conversations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_conversations_session_id"),
        "chat_conversations",
        ["session_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_chat_conversations_workspace_id"),
        "chat_conversations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "clients",
        sa.Column("workspace_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("nationality", sa.String(length=2), nullable=False),
        sa.Column("country_of_residence", sa.String(length=2), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("document_number", sa.String(length=100), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("created_by", app.shared.base_model.GUID(), nullable=False),
        sa.Column("acquisition_channel", sa.String(length=100), nullable=True),
        sa.Column("campaign_name", sa.String(length=255), nullable=True),
        sa.Column("churn_risk_level", sa.String(length=50), nullable=True),
        sa.Column("collections_risk_level", sa.String(length=50), nullable=True),
        sa.Column("last_failed_payment_at", sa.DateTime(), nullable=True),
        sa.Column("retention_sequence_status", sa.String(length=50), nullable=True),
        sa.Column("winback_eligible_flag", sa.Boolean(), nullable=False),
        sa.Column("chatwoot_contact_id", sa.String(length=100), nullable=True),
        sa.Column("zoho_contact_id", sa.String(length=100), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_email"), "clients", ["email"], unique=True)
    op.create_index(op.f("ix_clients_id"), "clients", ["id"], unique=False)
    op.create_table(
        "country_zone",
        sa.Column("zone_id", sa.BigInteger(), nullable=False),
        sa.Column("country_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["country_id"], ["countries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("zone_id", "country_id"),
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("workspace_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_documents_id"), "knowledge_documents", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_documents_workspace_id"),
        "knowledge_documents",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "leads",
        sa.Column("workspace_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("phone_e164", sa.String(length=50), nullable=False),
        sa.Column("phone_raw", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("preferred_language", sa.String(length=10), nullable=False),
        sa.Column("country_of_residence", sa.String(length=2), nullable=True),
        sa.Column("nationality", sa.String(length=2), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state_region", sa.String(length=100), nullable=True),
        sa.Column("source_channel", sa.String(length=100), nullable=True),
        sa.Column("campaign_name", sa.String(length=255), nullable=True),
        sa.Column("campaign_id", sa.String(length=255), nullable=True),
        sa.Column("adset_id", sa.String(length=255), nullable=True),
        sa.Column("ad_id", sa.String(length=255), nullable=True),
        sa.Column("utm_source", sa.String(length=100), nullable=True),
        sa.Column("utm_medium", sa.String(length=100), nullable=True),
        sa.Column("utm_campaign", sa.String(length=100), nullable=True),
        sa.Column("landing_page", sa.String(length=500), nullable=True),
        sa.Column("referral_source", sa.String(length=500), nullable=True),
        sa.Column("lead_status", sa.String(length=50), nullable=False),
        sa.Column("funnel_stage", sa.String(length=50), nullable=False),
        sa.Column("lead_score", sa.Integer(), nullable=False),
        sa.Column("intent_level", sa.String(length=50), nullable=True),
        sa.Column("first_contact_at", sa.DateTime(), nullable=True),
        sa.Column("last_conversation_at", sa.DateTime(), nullable=True),
        sa.Column("last_conversation_channel", sa.String(length=50), nullable=True),
        sa.Column("conversation_status", sa.String(length=50), nullable=True),
        sa.Column("whatsapp_opt_in_status", sa.Boolean(), nullable=False),
        sa.Column("chatwoot_contact_id", sa.String(length=100), nullable=True),
        sa.Column(
            "chatwoot_conversation_id_last", sa.String(length=100), nullable=True
        ),
        sa.Column("assigned_agent", sa.String(length=255), nullable=True),
        sa.Column("ai_handled_flag", sa.Boolean(), nullable=False),
        sa.Column("human_handoff_flag", sa.Boolean(), nullable=False),
        sa.Column("last_message_summary", sa.Text(), nullable=True),
        sa.Column("form_started", sa.Boolean(), nullable=False),
        sa.Column("form_completed", sa.Boolean(), nullable=False),
        sa.Column("checkout_started", sa.Boolean(), nullable=False),
        sa.Column("checkout_started_at", sa.DateTime(), nullable=True),
        sa.Column("checkout_completed", sa.Boolean(), nullable=False),
        sa.Column("abandoned_checkout_flag", sa.Boolean(), nullable=False),
        sa.Column("abandoned_checkout_at", sa.DateTime(), nullable=True),
        sa.Column("purchase_completed", sa.Boolean(), nullable=False),
        sa.Column("followup_whatsapp_sent", sa.Boolean(), nullable=False),
        sa.Column("followup_whatsapp_sent_at", sa.DateTime(), nullable=True),
        sa.Column("followup_sequence_step", sa.Integer(), nullable=False),
        sa.Column("next_followup_at", sa.DateTime(), nullable=True),
        sa.Column("converted_to_contact_flag", sa.Boolean(), nullable=False),
        sa.Column("converted_at", sa.DateTime(), nullable=True),
        sa.Column("backend_customer_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("zoho_lead_id", sa.String(length=100), nullable=True),
        sa.Column("snapshot_last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leads_email"), "leads", ["email"], unique=False)
    op.create_index(op.f("ix_leads_id"), "leads", ["id"], unique=False)
    op.create_index(op.f("ix_leads_phone_e164"), "leads", ["phone_e164"], unique=True)
    op.create_table(
        "payment_methods",
        sa.Column("user_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("stripe_payment_method_id", sa.String(length=255), nullable=False),
        sa.Column("card_brand", sa.String(length=50), nullable=True),
        sa.Column("card_last4", sa.String(length=4), nullable=True),
        sa.Column("card_exp_month", sa.Integer(), nullable=True),
        sa.Column("card_exp_year", sa.Integer(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_payment_method_id"),
    )
    op.create_index(
        op.f("ix_payment_methods_id"), "payment_methods", ["id"], unique=False
    )
    op.create_table(
        "plans",
        sa.Column("workspace_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("base_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("max_entry_age", sa.Integer(), nullable=False),
        sa.Column("max_renewal_age", sa.Integer(), nullable=False),
        sa.Column("repatriation_countries", sa.JSON(), nullable=False),
        sa.Column("terms_es", sa.Text(), nullable=True),
        sa.Column("terms_en", sa.Text(), nullable=True),
        sa.Column("stripe_price_id", sa.String(length=255), nullable=True),
        sa.Column("vesting_accidental_days", sa.Integer(), nullable=False),
        sa.Column("vesting_natural_days", sa.Integer(), nullable=False),
        sa.Column("vesting_suicide_days", sa.Integer(), nullable=False),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plans_id"), "plans", ["id"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("permission_id", app.shared.base_model.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "stripe_accounts",
        sa.Column("user_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("stripe_account_id", sa.String(length=255), nullable=False),
        sa.Column("account_type", sa.String(length=50), nullable=False),
        sa.Column("charges_enabled", sa.Boolean(), nullable=False),
        sa.Column("payout_enabled", sa.Boolean(), nullable=False),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_account_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_stripe_accounts_id"), "stripe_accounts", ["id"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("role_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("assigned_by", app.shared.base_model.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "user_workspaces",
        sa.Column("user_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("workspace_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "workspace_id"),
    )
    op.create_table(
        "age_ranges",
        sa.Column("plan_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("min_age", sa.Integer(), nullable=False),
        sa.Column("max_age", sa.Integer(), nullable=False),
        sa.Column(
            "surcharge_percentage", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("min_age < max_age", name="check_age_order"),
        sa.CheckConstraint(
            "surcharge_percentage >= 0", name="check_positive_surcharge"
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_age_ranges_id"), "age_ranges", ["id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("conversation_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["chat_conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_table(
        "country_configs",
        sa.Column("plan_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("country_name", sa.String(length=100), nullable=False),
        sa.Column(
            "base_price_override", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "country_code", name="uq_plan_country"),
    )
    op.create_index(
        op.f("ix_country_configs_id"), "country_configs", ["id"], unique=False
    )
    op.create_table(
        "plan_coverages",
        sa.Column("plan_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("coverage_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("override_limit", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("is_included", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["coverage_id"], ["coverages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("plan_id", "coverage_id"),
    )
    op.create_table(
        "plan_versions",
        sa.Column("plan_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("created_by", app.shared.base_model.GUID(), nullable=False),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "version_number", name="uq_plan_version"),
    )
    op.create_index(op.f("ix_plan_versions_id"), "plan_versions", ["id"], unique=False)
    op.create_table(
        "policies",
        sa.Column("workspace_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("policy_number", sa.String(length=50), nullable=False),
        sa.Column("client_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("lead_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("plan_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("plan_version_snapshot", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("base_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "surcharge_amount", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("final_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("pdf_path", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("issued_by", app.shared.base_model.GUID(), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_by", app.shared.base_model.GUID(), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["issued_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_number"),
    )
    op.create_index(op.f("ix_policies_id"), "policies", ["id"], unique=False)
    op.create_table(
        "beneficiaries",
        sa.Column("policy_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("kinship_type", sa.String(length=50), nullable=False),
        sa.Column("country_of_residence", sa.String(length=2), nullable=False),
        sa.Column("location_type", sa.String(length=50), nullable=False),
        sa.Column("coverage_status", sa.String(length=50), nullable=False),
        sa.Column(
            "individual_price", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("deceased_flag", sa.Boolean(), nullable=False),
        sa.Column("deceased_reported_at", sa.DateTime(), nullable=True),
        sa.Column("deceased_reported_by", sa.String(length=255), nullable=True),
        sa.Column("backend_api_call_sent", sa.Boolean(), nullable=False),
        sa.Column("backend_api_call_sent_at", sa.DateTime(), nullable=True),
        sa.Column("billing_adjustment_confirmed", sa.Boolean(), nullable=False),
        sa.Column("zoho_beneficiary_id", sa.String(length=100), nullable=True),
        sa.Column("snapshot_last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["policy_id"], ["policies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_beneficiaries_id"), "beneficiaries", ["id"], unique=False)
    op.create_table(
        "policy_status_history",
        sa.Column("policy_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("from_status", sa.String(length=30), nullable=True),
        sa.Column("to_status", sa.String(length=30), nullable=False),
        sa.Column("changed_by", app.shared.base_model.GUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["policy_id"], ["policies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_policy_status_history_id"),
        "policy_status_history",
        ["id"],
        unique=False,
    )
    op.create_table(
        "subscriptions",
        sa.Column("workspace_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("policy_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("plan_name", sa.String(length=100), nullable=True),
        sa.Column("plan_code", sa.String(length=100), nullable=True),
        sa.Column("monthly_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("billing_frequency", sa.String(length=50), nullable=False),
        sa.Column("mrr_snapshot", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("failed_payment_count", sa.Integer(), nullable=False),
        sa.Column("beneficiaries_count", sa.Integer(), nullable=False),
        sa.Column("current_period_start", sa.DateTime(), nullable=False),
        sa.Column("current_period_end", sa.DateTime(), nullable=False),
        sa.Column(
            "subscription_created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("subscription_activated_at", sa.DateTime(), nullable=True),
        sa.Column("renewal_date", sa.DateTime(), nullable=True),
        sa.Column("last_payment_date", sa.DateTime(), nullable=True),
        sa.Column("next_payment_due_date", sa.DateTime(), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("zoho_subscription_id", sa.String(length=100), nullable=True),
        sa.Column("snapshot_last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["policy_id"], ["policies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_id"),
        sa.UniqueConstraint("stripe_subscription_id"),
    )
    op.create_index(op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("workspace_id", app.shared.base_model.GUID(), nullable=True),
        sa.Column("policy_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_invoice_id", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("payment_type", sa.String(length=50), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("stripe_metadata", sa.JSON(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["policy_id"], ["policies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_transactions_stripe_payment_intent_id"),
        "transactions",
        ["stripe_payment_intent_id"],
        unique=False,
    )
    op.create_table(
        "claims",
        sa.Column("policy_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("beneficiary_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("reported_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["beneficiary_id"], ["beneficiaries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["policy_id"], ["policies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_claims_id"), "claims", ["id"], unique=False)
    op.create_table(
        "claim_expenses",
        sa.Column("claim_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("expense_type", sa.String(length=100), nullable=False),
        sa.Column("receipt_url", sa.String(length=500), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_claim_expenses_id"), "claim_expenses", ["id"], unique=False
    )
    op.create_table(
        "commission_distributions",
        sa.Column("claim_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("workspace_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_commission_distributions_id"),
        "commission_distributions",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_commission_distributions_id"), table_name="commission_distributions"
    )
    op.drop_table("commission_distributions")
    op.drop_index(op.f("ix_claim_expenses_id"), table_name="claim_expenses")
    op.drop_table("claim_expenses")
    op.drop_index(op.f("ix_claims_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(
        op.f("ix_transactions_stripe_payment_intent_id"), table_name="transactions"
    )
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(
        op.f("ix_policy_status_history_id"), table_name="policy_status_history"
    )
    op.drop_table("policy_status_history")
    op.drop_index(op.f("ix_beneficiaries_id"), table_name="beneficiaries")
    op.drop_table("beneficiaries")
    op.drop_index(op.f("ix_policies_id"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_plan_versions_id"), table_name="plan_versions")
    op.drop_table("plan_versions")
    op.drop_table("plan_coverages")
    op.drop_index(op.f("ix_country_configs_id"), table_name="country_configs")
    op.drop_table("country_configs")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_age_ranges_id"), table_name="age_ranges")
    op.drop_table("age_ranges")
    op.drop_table("user_workspaces")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_stripe_accounts_id"), table_name="stripe_accounts")
    op.drop_table("stripe_accounts")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_plans_id"), table_name="plans")
    op.drop_table("plans")
    op.drop_index(op.f("ix_payment_methods_id"), table_name="payment_methods")
    op.drop_table("payment_methods")
    op.drop_index(op.f("ix_leads_phone_e164"), table_name="leads")
    op.drop_index(op.f("ix_leads_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_email"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(
        op.f("ix_knowledge_documents_workspace_id"), table_name="knowledge_documents"
    )
    op.drop_index(op.f("ix_knowledge_documents_id"), table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    op.drop_table("country_zone")
    op.drop_index(op.f("ix_clients_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_email"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(
        op.f("ix_chat_conversations_workspace_id"), table_name="chat_conversations"
    )
    op.drop_index(
        op.f("ix_chat_conversations_session_id"), table_name="chat_conversations"
    )
    op.drop_index(op.f("ix_chat_conversations_id"), table_name="chat_conversations")
    op.drop_table("chat_conversations")
    op.drop_index(op.f("ix_audit_logs_workspace_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_user_id_created_at", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity_entity_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action_created_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_zones_name"), table_name="zones")
    op.drop_index(op.f("ix_zones_is_active"), table_name="zones")
    op.drop_index(op.f("ix_zones_id"), table_name="zones")
    op.drop_table("zones")
    op.drop_index(op.f("ix_workspaces_slug"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_id"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_stripe_events_id"), table_name="stripe_events")
    op.drop_index(op.f("ix_stripe_events_event_id"), table_name="stripe_events")
    op.drop_table("stripe_events")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_id"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_coverages_id"), table_name="coverages")
    op.drop_table("coverages")
    op.drop_index(op.f("ix_countries_phone_code"), table_name="countries")
    op.drop_index(op.f("ix_countries_is_active"), table_name="countries")
    op.drop_index(op.f("ix_countries_id"), table_name="countries")
    op.drop_index(op.f("ix_countries_continent_code"), table_name="countries")
    op.drop_table("countries")
    # ### end Alembic commands ###
