"""finance_system

Revision ID: eb37207d3580
Revises: 800269a4b3d2
Create Date: 2026-03-31 13:06:23.172430

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.shared.base_model


# revision identifiers, used by Alembic.
revision: str = "eb37207d3580"
down_revision: Union[str, Sequence[str], None] = "800269a4b3d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_currencies_code"), "currencies", ["code"], unique=True)
    op.create_index(op.f("ix_currencies_id"), "currencies", ["id"], unique=False)
    op.create_table(
        "units_of_measure",
        sa.Column("name", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("measure_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_units_of_measure_id"), "units_of_measure", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_units_of_measure_measure_type"),
        "units_of_measure",
        ["measure_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_units_of_measure_status"), "units_of_measure", ["status"], unique=False
    )
    op.create_table(
        "company_commission_users",
        sa.Column("company_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("user_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "commission_percentage", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "user_id", name="uq_company_commission_user"),
    )
    op.create_index(
        op.f("ix_company_commission_users_id"),
        "company_commission_users",
        ["id"],
        unique=False,
    )
    op.create_table(
        "business_unit_commission_users",
        sa.Column("business_unit_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column("user_id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "commission_percentage", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("id", app.shared.base_model.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["business_unit_id"], ["business_units.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_unit_id", "user_id", name="uq_bu_commission_user"
        ),
    )
    op.create_index(
        op.f("ix_business_unit_commission_users_id"),
        "business_unit_commission_users",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_business_unit_commission_users_id"),
        table_name="business_unit_commission_users",
    )
    op.drop_table("business_unit_commission_users")
    op.drop_index(
        op.f("ix_company_commission_users_id"), table_name="company_commission_users"
    )
    op.drop_table("company_commission_users")
    op.drop_index(op.f("ix_units_of_measure_status"), table_name="units_of_measure")
    op.drop_index(
        op.f("ix_units_of_measure_measure_type"), table_name="units_of_measure"
    )
    op.drop_index(op.f("ix_units_of_measure_id"), table_name="units_of_measure")
    op.drop_table("units_of_measure")
    op.drop_index(op.f("ix_currencies_id"), table_name="currencies")
    op.drop_index(op.f("ix_currencies_code"), table_name="currencies")
    op.drop_table("currencies")
    # ### end Alembic commands ###
